import type { TestScenario } from "@/lib/testing/test-types";

export const TEST_SCENARIOS: TestScenario[] = [
  {
    id: "EVENING_EATING",
    name: "Evening Eating / Arrival Home",
    businessModel: "weight_management",
    userProfile: "Adult trying to manage evening eating after arriving home from work.",
    objective: "Identify that arrival home acts as a behavioral trigger for snacking and overeating.",
    maxMessages: 12,
    maxSessions: 3,
    initialSessionMode: "NEW_SESSION",
    simulationInstructions: [
      "Reveal information gradually rather than all at once.",
      "Do not immediately reveal the full trigger pattern.",
      "Answer naturally and briefly when the system asks clarifying questions.",
      "If the system identifies a likely pattern, acknowledge it and add one subtle detail.",
      "Stay within the objective and avoid unrelated information.",
    ],
    mockMessages: [
      "Akşamları kendimi tutamıyorum.",
      "Eve geldiğimde direkt mutfağa gidiyorum.",
      "Önce üstümü değiştirip biraz dinleniyorum, sonra mutfağa gidiyorum.",
      "Aslında çok aç değilim ama yine de yiyorum.",
      "İşten stresli geldiğim günlerde daha fazla oluyor.",
      "Sanırım eve gelmek benim için bir tetikleyici.",
      "Bunu fark edince daha iyi kontrol edebiliyorum.",
      "Bazen sadece rutin haline geldiği için oluyor.",
    ],
    expectedStates: ["DISCOVERY", "PATTERN_EMERGING", "INSIGHT_READY", "INSIGHT_DELIVERED"],
    assertions: [
      "must_detect_evening_pattern",
      "must_not_claim_unstated_fact",
      "must_ask_followup_before_intervention",
      "must_reach_insight_ready",
      "must_keep_same_session",
    ],
  },
  {
    id: "EMOTIONAL_EATING",
    name: "Emotional Eating",
    businessModel: "weight_management",
    userProfile: "Adult who turns to food when feeling overwhelmed, disappointed, or emotionally activated.",
    objective: "Identify emotional triggers rather than hunger as the main driver behind episodes.",
    maxMessages: 10,
    maxSessions: 3,
    initialSessionMode: "NEW_SESSION",
    simulationInstructions: [
      "Frame food as a coping mechanism, not a nutritional need.",
      "Mention emotional context before labeling it as a pattern.",
      "Be specific about what feeling precedes an eating episode.",
      "Keep the response realistic and avoid overdramatizing.",
    ],
    mockMessages: [
      "Bazen kendimi kötü hissettiğim anlarda abartılı yiyorum.",
      "Yemek beni biraz sakinleştiriyor gibi hissediyorum.",
      "Özellikle hayal kırıklığı yaşadığım günlerde daha çok oluyor.",
      "Duygusal olarak yıprandığımda yemek bir kaçış gibi geliyor.",
      "Aslında aç olmak kadar stres de etkiliyor.",
      "Kendimi yetersiz hissettiğim zamanlarda daha çok atıştırıyorum.",
    ],
    expectedStates: ["DISCOVERY", "PATTERN_EMERGING", "INSIGHT_READY"],
    assertions: [
      "must_detect_emotional_trigger",
      "must_not_claim_unstated_fact",
      "must_reach_insight_ready",
    ],
  },
  {
    id: "WEEKEND_BREAKDOWN",
    name: "Weekend Breakdown",
    businessModel: "weight_management",
    userProfile: "Adult with a structured week but a less controlled weekend pattern.",
    objective: "Surface the weekend as a high-risk period that undermines healthy control.",
    maxMessages: 11,
    maxSessions: 3,
    initialSessionMode: "NEW_SESSION",
    simulationInstructions: [
      "Keep weekdays as the baseline and weekend as the disruption.",
      "Describe how routine dissolves on weekends.",
      "Be honest about flexibility and social plans.",
      "The key risk is unstructured eating, not a medical explanation.",
    ],
    mockMessages: [
      "Haftaiçi daha kontrollü oluyorum.",
      "Hafta sonu biraz daha serbest hissediyorum.",
      "İnsanlar daha geç yiyor, ben de onlarla birlikte yiyorum.",
      "Pazartesiye kadar düzen bozuluyor gibi geliyor.",
      "Bazen günün akışı da etkiliyor.",
      "Hafta sonu daha çok yemek, daha az planlama oluyor.",
    ],
    expectedStates: ["DISCOVERY", "PATTERN_EMERGING", "INSIGHT_READY"],
    assertions: [
      "must_detect_weekend_pattern",
      "must_keep_same_session",
      "must_reach_insight_ready",
    ],
  },
  {
    id: "SOCIAL_EATING",
    name: "Social Eating",
    businessModel: "weight_management",
    userProfile: "Adult who eats more in social contexts and while eating out with others.",
    objective: "Identify social situations as a trigger for excess consumption.",
    maxMessages: 10,
    maxSessions: 3,
    initialSessionMode: "NEW_SESSION",
    simulationInstructions: [
      "Show social eating as a contextual trigger, not a moral failure.",
      "Use specific examples like dinner, gatherings, or eating out.",
      "Let the user reveal the pattern through real-life situations gradually.",
    ],
    mockMessages: [
      "Arkadaşlarla dışarıda yemek yemeye gittiğimde daha çok yiyorum.",
      "Kendi başıma yediğimden daha fazla oluyor.",
      "Bir de herkes yemek yerken ben de devam ediyorum.",
      "Yemekler sosyal bir etkinlik gibi oluyor.",
      "Aç olmasam bile o anda bitirmeye çalışıyorum.",
    ],
    expectedStates: ["DISCOVERY", "PATTERN_EMERGING", "INSIGHT_READY"],
    assertions: [
      "must_detect_social_pattern",
      "must_not_claim_unstated_fact",
      "must_reach_insight_ready",
    ],
  },
  {
    id: "BOREDOM_EATING",
    name: "Boredom Eating",
    businessModel: "weight_management",
    userProfile: "Adult who snacks when idle or mentally disengaged.",
    objective: "Determine boredom and inactivity as a recurring snacking cue.",
    maxMessages: 9,
    maxSessions: 3,
    initialSessionMode: "NEW_SESSION",
    simulationInstructions: [
      "Show that the user eats when unoccupied, not always when hungry.",
      "Mention low-energy or rest periods as trigger contexts.",
      "Avoid a full behavioral diagnosis too early.",
    ],
    mockMessages: [
      "Boş vakitlerim olduğunda atıştırıyorum.",
      "Bazen canım sıkılıyor, o anda yemek istiyorum.",
      "İçim sıkıldığında mutfağa gidiyorum.",
      "Aç olmadan da olabilir.",
      "İşin ortasında durup bir şeyler yiyorum.",
    ],
    expectedStates: ["DISCOVERY", "PATTERN_EMERGING", "INSIGHT_READY"],
    assertions: [
      "must_detect_boredom_pattern",
      "must_not_claim_unstated_fact",
      "must_reach_insight_ready",
    ],
  },
  {
    id: "LATE_NIGHT_EATING",
    name: "Late Night Eating",
    businessModel: "weight_management",
    userProfile: "Adult who eats late at night while winding down or using screens.",
    objective: "Identify late-night routine as the dominant eating trigger.",
    maxMessages: 10,
    maxSessions: 3,
    initialSessionMode: "NEW_SESSION",
    simulationInstructions: [
      "Keep late-night timing explicit and consistent.",
      "Use screen time, winding down, or nighttime routine as context.",
      "Do not conflate hunger with boredom until confirmed.",
    ],
    mockMessages: [
      "Gece geç saatlerde daha çok yiyorum.",
      "Televizyon izlerken veya telefon başında atıştırıyorum.",
      "Uyumadan önce bir şeyler yemek beni rahatlatıyor.",
      "Geceleri aç olmaksızın da olabilir.",
      "Bu ritim benim için çok belirgin.",
    ],
    expectedStates: ["DISCOVERY", "PATTERN_EMERGING", "INSIGHT_READY"],
    assertions: [
      "must_detect_late_night_pattern",
      "must_keep_same_session",
      "must_reach_insight_ready",
    ],
  },
  {
    id: "REPEATED_DIET_FAILURE",
    name: "Repeated Diet Failure",
    businessModel: "weight_management",
    userProfile: "Adult with repeated cycles of strict dieting followed by overeating and guilt.",
    objective: "Identify the pattern of all-or-nothing dieting and rebound eating.",
    maxMessages: 12,
    maxSessions: 3,
    initialSessionMode: "NEW_SESSION",
    simulationInstructions: [
      "Describe the cycle without blaming the user.",
      "Reveal the strict start, then the rebound pattern.",
      "Frame the issue as a behavioral pattern, not a willpower problem.",
    ],
    mockMessages: [
      "Diyet başlatınca çok disiplinli oluyorum.",
      "Ama birkaç gün sonra kendimi yemeğe daha fazla kaptırıyorum.",
      "Biraz kaçınca kendimi daha çok suçlu hissediyorum.",
      "Sonra yine her şeyi bırakıp çok fazla yiyorum.",
      "Bu döngü defalarca tekrarlıyor.",
      "Diyetin kendisi bence sorun oluyor, değil mi?",
    ],
    expectedStates: ["DISCOVERY", "PATTERN_EMERGING", "INSIGHT_READY"],
    assertions: [
      "must_detect_rebound_cycle",
      "must_not_claim_unstated_fact",
      "must_reach_insight_ready",
    ],
  },
  {
    id: "DEFENSIVE_USER",
    name: "Defensive User",
    businessModel: "weight_management",
    userProfile: "Adult who feels judged and responds defensively when discussing eating habits.",
    objective: "Keep the conversation collaborative while the user resists direct labeling.",
    maxMessages: 11,
    maxSessions: 3,
    initialSessionMode: "NEW_SESSION",
    simulationInstructions: [
      "The user may resist or deny the pattern at first.",
      "Use validation and careful phrasing instead of labeling.",
      "Let the user reveal risk triggers without direct confrontation.",
      "Remain gentle and avoid shaming language.",
    ],
    mockMessages: [
      "Bunu sadece bir kez konuşmak istemiyorum.",
      "Yemek yediğim için suçlu hissetmiyorum.",
      "Benim davranışım çok normal, sanki beni sorguluyorsunuz.",
      "Belki de sadece yoğun bir iş dönemi.",
      "Aç olmamış olsam da biraz atıştırıyorum.",
      "Bu konu için çok da net bir şey söylemek istemiyorum.",
    ],
    expectedStates: ["DISCOVERY", "VALIDATION", "PATTERN_EMERGING"],
    assertions: [
      "must_validate_without_shaming",
      "must_keep_session_collaborative",
      "must_reach_pattern_emerging",
    ],
  },
  {
    id: "MINIMAL_DISCLOSURE",
    name: "Minimal Disclosure",
    businessModel: "weight_management",
    userProfile: "Adult who gives only brief responses and avoids detailed explanations.",
    objective: "Extract only the minimum needed evidence while maintaining rapport.",
    maxMessages: 8,
    maxSessions: 2,
    initialSessionMode: "NEW_SESSION",
    simulationInstructions: [
      "Keep answers short and non-detailed.",
      "Only add a new fact when directly asked.",
      "Avoid making assumptions beyond the user’s wording.",
      "Nudge gently toward more clarity only when needed.",
    ],
    mockMessages: [
      "Genelde akşamları yiyorum.",
      "Biraz da streslendiğimde.",
      "Eve gelince oluyor.",
      "Bir şeyler atıştırıyorum.",
      "Özetle, bu işin temposu etkiliyor.",
    ],
    expectedStates: ["DISCOVERY", "VALIDATION", "INSIGHT_READY"],
    assertions: [
      "must_ask_followup_before_intervention",
      "must_not_over_assume",
      "must_keep_same_session",
    ],
  },
  {
    id: "RESISTANT_USER",
    name: "Resistant User",
    businessModel: "weight_management",
    userProfile: "Adult who is skeptical of coaching and resists insight framing.",
    objective: "Preserve trust while gradually exposing a pattern without forcing a conclusion.",
    maxMessages: 10,
    maxSessions: 3,
    initialSessionMode: "NEW_SESSION",
    simulationInstructions: [
      "Do not push a conclusion too early.",
      "Use validation, curiosity, and gentle reflection.",
      "Let the user test the idea rather than accept a label instantly.",
      "Keep the voice calm and collaborative.",
    ],
    mockMessages: [
      "Bana bunu yapmamı söylemek için çok erken.",
      "İşin içinde biraz stres var ama bu her zaman değil.",
      "Yemek beni sakinleştiriyor, ama bu sadece geçici bir şey.",
      "Belki de yoğun günlerde daha çok oluyor.",
      "Bunu fark etmem biraz zaman aldı.",
    ],
    expectedStates: ["DISCOVERY", "VALIDATION", "PATTERN_EMERGING", "INSIGHT_READY"],
    assertions: [
      "must_validate_before_intervention",
      "must_not_force_insight",
      "must_keep_session_collaborative",
    ],
  },
];

export function findScenarioById(id: string): TestScenario | undefined {
  return TEST_SCENARIOS.find((scenario) => scenario.id === id);
}

export function getDefaultScenario(): TestScenario {
  return TEST_SCENARIOS[0];
}
